### PR TITLE
WebSocket

### PR DESCRIPTION
**Pull request by szk2s**
Make API for debugging s2m
- for development of s2m library (other repository), you need visualizing data.
- See sendPartials.js and sendPlotContent.js at [s2m examples folder](https://github.com/szk2s/spectrum2mpe/tree/socket/examples)

### CODE REVIEW

**Comment by szk2s** [comment]
Hi @zigen , I connect s2m and spectral-mpe-editor with socket. Can you review this PR and [this](https://github.com/szk2s/spectrum2mpe/pull/35) , please?

**Comment by zigen** [comment]
hmm, you mean `socket` is websocket? 
it's completely defference from udp/tcp socket. (socket.io seems kind of misleading)
it'd be better to change name socket -> websocket.

**Comment by szk2s** [comment]
@zigen, Socket.io is not a socket? It's real joke, haha.
I renamed this PR, but it is hard to rename remote branch name....

**Comment by zigen** [comment]
just use git branch -m and then re-create PR

**Comment by szk2s** [comment]
Ok , I'll do it just now

**Pull request closed without merging**
